name: radarr
display_name: Radarr
description: Movie collection manager for Usenet and BitTorrent users
category: media
homepage: https://radarr.video
version: latest
vars:
  version:
    type: string
    default: latest
    description: Docker image tag
requires: []
suggests:
  - prowlarr
ports:
  - 7878
volumes:
  - name: config
    path: /config
  - name: movies
    path: /movies
    external: true
  - name: downloads
    path: /downloads
    external: true
