name: portainer
display_name: Portainer
description: Docker management UI
category: management
homepage: https://www.portainer.io
version: latest
vars:
  version:
    type: string
    default: latest
    description: Docker image tag
ports:
  - 9443
volumes:
  - name: data
    path: /data
