name: dasherr
display_name: Dasherr
description: Minimal, clean application dashboard for your homelab
category: management
homepage: https://github.com/erohtar/Dasherr
version: latest
exposure: external
requires:
  - traefik
vars:
  version:
    type: string
    default: latest
    description: Docker image tag
ports:
  - 3000
host_ports: []
volumes:
  - name: settings
    path: /www/public/settings
