name: lidarr
display_name: Lidarr
description: Music collection manager for Usenet and BitTorrent users
category: media
homepage: https://lidarr.audio
version: latest
suggests:
  - prowlarr
vars:
  version:
    type: string
    default: latest
    description: Docker image tag
ports:
  - 8686
host_ports: []
volumes:
  - name: config
    path: /config
  - name: music
    path: /music
    external: true
  - name: downloads
    path: /downloads
    external: true
